#!/bin/bash

hasError=false

for file in ./vinlang_src/correct/*; do
  echo "Test $file"
  go run ./cmd/compiler/main.go "$file"
  if [ $? -eq 1 ]
  then
    hasError=true
  fi
done

for file in ./vinlang_src/error/*; do
  echo "Test $file"
  go run ./cmd/compiler/main.go "$file"
  if [ $? -eq 0 ]
  then
    hasError=true
  fi
done

if $hasError; then
  exit 1
fi
exit 0